### ISSUE TITLE
O

### ISSUE THREAD

**Issue by DGiless** [TheLazyGeekGuy/DIY-Waves-Soundgrid-Server#10]
## Report a working configuration

MotherBoard : ASUS B85 Plus
CPU : I5 4570 S
RAM : 8Go
Ethernet : Realtek R8169
Price : recycled PC
H-Reverb Test result :
Test version :

Report a working configuration

**Additional context**
Add any other context or information if needed
initiated on V12.7 server version, --> safe mode
Firmware updated to 14.9.59, no more safe mode :)
Tests in progress

**Comment by TheLazyGeekGuy** [comment]
List updated : thank you
