### ISSUE TITLE
This project is not dead, isnt?

### ISSUE THREAD

**Issue by gavalierm** [TheLazyGeekGuy/DIY-Waves-Soundgrid-Server#20]
Hey guys, this is not dead project i think.

Still is many Emotion LV1 users outhere which have custom servers.

**Comment by Sebigamer4** [comment]
also +1 for changing the readme so its clearer, that DIY Soundgrid servers arent dead, but only Waves studio is no longer supported

But theres still  Superrack Soundgrid and LV1, so the main topic of custom soundgrid server builds is still a big thing

**Comment by RJ3** [comment]
> only Waves studio is no longer supported

Is this supposed to say SoundGrid Studio?
