### ISSUE TITLE
HP Z220 Workstation

### ISSUE THREAD

**Issue by sennysoon** [TheLazyGeekGuy/DIY-Waves-Soundgrid-Server#3]
## Report a working configuration

MotherBoard :  HP Z220 SFF (C216 chipset) 
CPU: i7-3770 @ 3.5GHz
Ethernet : Intel 82579LM (onboard)
Price : N/A (donation)
H-Reverb Test result : 24 mono / 12 stereo
Test version : 12.8.0.320

Report a working configuration

**Additional context**
(12039680)
1 x 16GB RAM
96kHz, 80 samples latency
0 errors at 30mins
reference at same settings: Server Extreme C stable at 28 x Hverbs (mono)

**Comment by TheLazyGeekGuy** [comment]
Thank you !
